{
  try {
    return customChange.validate(database);
  }
 catch (  Throwable e) {
    return new ValidationErrors().addError("Exception thrown calling " + getClassName() + ".validate():"+ e.getMessage());
  }
}
